version: 2.1
parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""
orbs:
  slack: circleci/slack@4.12.5
jobs:
  build:
    docker:
      - image: alpine:3.12  # primary executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "86:1c:b6:e2:07:f7:e6:e5:7f:24:96:c5:7e:2f:af:c2"
            - "f2:9a:75:b8:82:b3:08:63:3d:9c:71:1d:14:2a:fa:18"
      - checkout
      - run: apk add python2
      - run: virtualenv -p python2 venv
      - run: venv/bin/pip install nose==1.3.7
      - run: venv/bin/nosetests
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  build_and_test:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - build:
          context:
            - Slack
